//! Native shell owner: `aux_metadata`.

use super::*;

// -----------------------------------------------------------------------------
// F2-02 — Auxiliary window factory (non-Main HWNDs).
// -----------------------------------------------------------------------------
//
// Closes §8.1 row 7 (`ShowWindow(non-Main)` / `HideWindow(non-Main)`), §8.1
// row 5 (`ContextMenu` host HWND) and §8.1 row 4 (`Tooltip` host HWND). The
// per-kind window class names below give every aux WindowKind its own atom
// so wndproc routing stays unambiguous; the OS interns each class once via
// `RegisterClassExW`'s `ERROR_CLASS_ALREADY_EXISTS` short-circuit, so a
// re-show of the same kind reuses the registered class without paying the
// register cost twice.

pub(super) const AUX_CLASS_ICON_PICKER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'I' as u16,
    b'c' as u16,
    b'o' as u16,
    b'n' as u16,
    b'P' as u16,
    b'k' as u16,
    0,
];
pub(super) const AUX_CLASS_CAPSULE_PICKER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'C' as u16,
    b'a' as u16,
    b'p' as u16,
    b's' as u16,
    b'P' as u16,
    b'k' as u16,
    0,
];
pub(super) const AUX_CLASS_CONTEXT_MENU: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'C' as u16,
    b't' as u16,
    b'x' as u16,
    b'M' as u16,
    b'n' as u16,
    b'u' as u16,
    0,
];
pub(super) const AUX_CLASS_TOOLTIP: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'T' as u16,
    b'i' as u16,
    b'p' as u16,
    0,
];
pub(super) const AUX_CLASS_DRAG_PREVIEW: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'D' as u16,
    b'r' as u16,
    b'g' as u16,
    0,
];
pub(super) const AUX_CLASS_SETTINGS: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'S' as u16,
    b'e' as u16,
    b't' as u16,
    b's' as u16,
    0,
];
pub(super) const AUX_CLASS_ABOUT: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'A' as u16,
    b'b' as u16,
    b'o' as u16,
    b'u' as u16,
    b't' as u16,
    0,
];
pub(super) const AUX_CLASS_MINIBAR: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'M' as u16,
    b'b' as u16,
    b'a' as u16,
    b'r' as u16,
    0,
];
// F2 bridge — class names for the 5 wizard/overlay variants added to
// WindowKind. Same allocation-free static pattern.
pub(super) const AUX_CLASS_PALETTE_PICKER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'P' as u16,
    b'a' as u16,
    b'l' as u16,
    b'P' as u16,
    b'k' as u16,
    0,
];
pub(super) const AUX_CLASS_RULES_WIZARD: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'R' as u16,
    b'u' as u16,
    b'l' as u16,
    b'W' as u16,
    b'z' as u16,
    0,
];
pub(super) const AUX_CLASS_BULK_MANAGER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'B' as u16,
    b'l' as u16,
    b'k' as u16,
    b'M' as u16,
    b'g' as u16,
    0,
];
pub(super) const AUX_CLASS_ZONE_EDITOR: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'Z' as u16,
    b'n' as u16,
    b'E' as u16,
    b'd' as u16,
    b'r' as u16,
    0,
];
pub(super) const AUX_CLASS_ITEM_FILE_RENAME: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'I' as u16,
    b't' as u16,
    b'm' as u16,
    b'R' as u16,
    b'n' as u16,
    0,
];
pub(super) const AUX_CLASS_SUGGESTOR: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'S' as u16,
    b'g' as u16,
    b's' as u16,
    b't' as u16,
    0,
];
pub(super) const AUX_CLASS_TIMELINE: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'T' as u16,
    b'i' as u16,
    b'm' as u16,
    b'e' as u16,
    0,
];
pub(super) const AUX_CLASS_SNAPSHOT_PICKER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'S' as u16,
    b'n' as u16,
    b'a' as u16,
    b'p' as u16,
    0,
];
pub(super) const AUX_CLASS_SEARCH: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'A' as u16,
    b'u' as u16,
    b'x' as u16,
    b'S' as u16,
    b'e' as u16,
    b'a' as u16,
    b'r' as u16,
    b'c' as u16,
    b'h' as u16,
    0,
];

/// Class name + window title for each non-Main `WindowKind`. Returning
/// `&'static [u16]` for both keeps the aux factory allocation-free (§10).
pub(super) fn aux_class_for(kind: WindowKind) -> &'static [u16] {
    match kind {
        WindowKind::Main => CLASS_NAME,
        WindowKind::IconPicker => AUX_CLASS_ICON_PICKER,
        WindowKind::CapsulePicker => AUX_CLASS_CAPSULE_PICKER,
        WindowKind::ContextMenu => AUX_CLASS_CONTEXT_MENU,
        WindowKind::Tooltip => AUX_CLASS_TOOLTIP,
        WindowKind::DragPreview => AUX_CLASS_DRAG_PREVIEW,
        WindowKind::Settings => AUX_CLASS_SETTINGS,
        WindowKind::About => AUX_CLASS_ABOUT,
        WindowKind::MiniBar => AUX_CLASS_MINIBAR,
        WindowKind::PalettePicker => AUX_CLASS_PALETTE_PICKER,
        WindowKind::RulesWizard => AUX_CLASS_RULES_WIZARD,
        WindowKind::BulkManager => AUX_CLASS_BULK_MANAGER,
        WindowKind::ZoneEditor => AUX_CLASS_ZONE_EDITOR,
        WindowKind::ItemFileRename => AUX_CLASS_ITEM_FILE_RENAME,
        WindowKind::Suggestor => AUX_CLASS_SUGGESTOR,
        WindowKind::Timeline => AUX_CLASS_TIMELINE,
        WindowKind::SnapshotPicker => AUX_CLASS_SNAPSHOT_PICKER,
        WindowKind::Search => AUX_CLASS_SEARCH,
    }
}

pub(super) const AUX_TITLE_ICON_PICKER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'I' as u16,
    b'c' as u16,
    b'o' as u16,
    b'n' as u16,
    0,
];
pub(super) const AUX_TITLE_CAPSULE_PICKER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'P' as u16,
    b'i' as u16,
    b'c' as u16,
    b'k' as u16,
    0,
];
pub(super) const AUX_TITLE_CONTEXT_MENU: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'M' as u16,
    b'e' as u16,
    b'n' as u16,
    b'u' as u16,
    0,
];
pub(super) const AUX_TITLE_TOOLTIP: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'T' as u16,
    b'i' as u16,
    b'p' as u16,
    0,
];
pub(super) const AUX_TITLE_DRAG_PREVIEW: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'D' as u16,
    b'r' as u16,
    b'a' as u16,
    b'g' as u16,
    0,
];
pub(super) const AUX_TITLE_SETTINGS: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'S' as u16,
    b'e' as u16,
    b't' as u16,
    0,
];
pub(super) const AUX_TITLE_ABOUT: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'A' as u16,
    b'b' as u16,
    b'o' as u16,
    b'u' as u16,
    b't' as u16,
    0,
];
pub(super) const AUX_TITLE_MINIBAR: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'B' as u16,
    b'a' as u16,
    b'r' as u16,
    0,
];
// F2 bridge — display titles for the 5 wizard/overlay variants.
pub(super) const AUX_TITLE_PALETTE_PICKER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'P' as u16,
    b'a' as u16,
    b'l' as u16,
    b'e' as u16,
    b't' as u16,
    b't' as u16,
    b'e' as u16,
    0,
];
pub(super) const AUX_TITLE_RULES_WIZARD: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'R' as u16,
    b'u' as u16,
    b'l' as u16,
    b'e' as u16,
    b's' as u16,
    0,
];
pub(super) const AUX_TITLE_BULK_MANAGER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'B' as u16,
    b'u' as u16,
    b'l' as u16,
    b'k' as u16,
    0,
];
pub(super) const AUX_TITLE_ZONE_EDITOR: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'E' as u16,
    b'd' as u16,
    b'i' as u16,
    b't' as u16,
    0,
];
pub(super) const AUX_TITLE_ITEM_FILE_RENAME: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'R' as u16,
    b'e' as u16,
    b'n' as u16,
    b'a' as u16,
    b'm' as u16,
    b'e' as u16,
    0,
];
pub(super) const AUX_TITLE_SUGGESTOR: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'S' as u16,
    b'u' as u16,
    b'g' as u16,
    0,
];
pub(super) const AUX_TITLE_TIMELINE: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'T' as u16,
    b'i' as u16,
    b'm' as u16,
    b'e' as u16,
    0,
];
pub(super) const AUX_TITLE_SNAPSHOT_PICKER: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'S' as u16,
    b'n' as u16,
    b'a' as u16,
    b'p' as u16,
    0,
];
pub(super) const AUX_TITLE_SEARCH: &[u16] = &[
    b'B' as u16,
    b'e' as u16,
    b'n' as u16,
    b't' as u16,
    b'o' as u16,
    b'D' as u16,
    b'e' as u16,
    b's' as u16,
    b'k' as u16,
    b' ' as u16,
    b'S' as u16,
    b'e' as u16,
    b'a' as u16,
    b'r' as u16,
    b'c' as u16,
    b'h' as u16,
    0,
];

pub(super) fn aux_title_for(kind: WindowKind) -> &'static [u16] {
    match kind {
        WindowKind::Main => WIN_TITLE,
        WindowKind::IconPicker => AUX_TITLE_ICON_PICKER,
        WindowKind::CapsulePicker => AUX_TITLE_CAPSULE_PICKER,
        WindowKind::ContextMenu => AUX_TITLE_CONTEXT_MENU,
        WindowKind::Tooltip => AUX_TITLE_TOOLTIP,
        WindowKind::DragPreview => AUX_TITLE_DRAG_PREVIEW,
        WindowKind::Settings => AUX_TITLE_SETTINGS,
        WindowKind::About => AUX_TITLE_ABOUT,
        WindowKind::MiniBar => AUX_TITLE_MINIBAR,
        WindowKind::PalettePicker => AUX_TITLE_PALETTE_PICKER,
        WindowKind::RulesWizard => AUX_TITLE_RULES_WIZARD,
        WindowKind::BulkManager => AUX_TITLE_BULK_MANAGER,
        WindowKind::ZoneEditor => AUX_TITLE_ZONE_EDITOR,
        WindowKind::ItemFileRename => AUX_TITLE_ITEM_FILE_RENAME,
        WindowKind::Suggestor => AUX_TITLE_SUGGESTOR,
        WindowKind::Timeline => AUX_TITLE_TIMELINE,
        WindowKind::SnapshotPicker => AUX_TITLE_SNAPSHOT_PICKER,
        WindowKind::Search => AUX_TITLE_SEARCH,
    }
}
