use super::{
    ALL_ICON_KINDS,
    AppRoot,
    AuxiliaryEscapeAction,
    BACKEND_EVENT_POLL_TIMER_ID,
    BentoItem,
    BentoZone,
    BulkZoneUpdate,
    CONTEXT_MENU_INPUT_TIMER_ID,
    Command,
    ContextCapsuleWindow,
    DispatchPoint,
    DispatchSize,
    DragSelectionRelease,
    EventDispatcher,
    GHOST_PASSTHROUGH_TIMER_ID,
    GridPosition,
    HOVER_FRAME_POLL_MS,
    HOVER_FRAME_TIMER_ID,
    HWND,
    ITEM_CONTEXT_COPY_PATH_ID,
    ITEM_CONTEXT_DELETE_FILE_ID,
    ITEM_CONTEXT_MOVE_ZONE_BASE_ID,
    ITEM_CONTEXT_OPEN_ID,
    ITEM_CONTEXT_REMOVE_ID,
    ITEM_CONTEXT_RENAME_FILE_ID,
    ITEM_CONTEXT_REVEAL_ID,
    ITEM_CONTEXT_TOGGLE_WIDE_ID,
    ItemContextAction,
    ItemContextDispatch,
    ItemType,
    LayoutData,
    LiveContextWindow,
    MiniBar,
    MiniBarRoster,
    PendingItemDragOut,
    RESIDENT_MEMORY_TRIM_TIMER_ID,
    RecoveryIconRestoreOutcome,
    RecycleDeleteOutcome,
    RelativePosition,
    RelativeSize,
    SETTING_ACTIVE_THEME,
    SETTING_APPEARANCE_ACCENT_COLOR,
    SETTING_BACKUP_LAST_CREATED,
    SETTING_BACKUP_LAST_RESTORED,
    SETTING_DEBUG_OVERLAY,
    SETTING_DISPLAY_LOCALE,
    SETTING_ENCRYPTION_MODE,
    SETTING_MINIBAR_PINNED_ZONES,
    SETTING_STEALTH_ENABLED,
    SETTING_THEME_BASE_ACCENT,
    SETTING_UPDATES_AUTO_DOWNLOAD,
    SETTING_UPDATES_CHECK_FREQUENCY,
    SETTING_ZONE_DISPLAY_MODE,
    STACK_TRAY_MEMORY_TRIM_TIMER_ID,
    STARTUP_MEMORY_TRIM_TIMER_ID,
    StartupLayoutLoadSource,
    TRAY_ICON_RETRY_TIMER_ID,
    VK_A_KEY,
    VK_BACKSPACE,
    VK_D_KEY,
    VK_DOWN_KEY,
    VK_ENTER,
    VK_ESCAPE_KEY,
    VK_N_KEY,
    VK_P_KEY,
    VK_SPACE_KEY,
    WPARAM,
    WindowRegistry,
    WindowState,
    ZONE_CONTEXT_BIND_LIVE_FOLDER_ID,
    ZoneContextAction,
    accent_hex_to_colorref,
    active_theme_id_is_builtin,
    add_item_to_zone_with,
    apply_active_theme_to_app,
    apply_bulk_layout_algorithm,
    apply_bulk_zone_updates,
    apply_bulk_zone_visibility,
    apply_hotkey_binding,
    apply_hotkey_setting_to_runtime,
    apply_item_context_dispatch_with,
    apply_locale_wire,
    apply_rules_execution_plan,
    apply_rules_move_to_folder,
    apply_setting_value_to_app,
    apply_theme_base_accent_to_app,
    apply_update_event_to_app,
    async_mouse_button_active,
    auxiliary_escape_action,
    bento_zones_from_app,
    bool_setting_command_for,
    build_tray_delete_icon_data,
    build_tray_notify_icon_data,
    bulk_layout_target_ids,
    bulk_manager_rows_from_app,
    bulk_metadata_updates_for_target_ids,
    bulk_text_update_for_id,
    bulk_text_updates_for_selected,
    capture_context_capsule_for_path,
    capture_current_timeline_snapshot,
    capture_recovery_bundle,
    centered_fixed_aux_host_rect,
    clamp_zone_rect_to_viewport,
    clear_stack_bloom_surface,
    close_settings_surface,
    collapse_zone_from_header,
    colorref_to_accent_hex,
    compute_bulk_layout_positions,
    consume_dispatcher,
    context_capsule_payload_is_json,
    context_menu_next_hit,
    copy_item_path_with,
    create_settings_backup_from_vault,
    current_minibar_pins_csv,
    decode_context_capsule_envelope,
    decode_context_capsule_zones,
    default_hotkey_bindings,
    delete_context_capsule_for_path,
    delete_item_file_to_recycle_bin_using,
    delete_path_to_recycle_bin_with,
    desktop_source_rows_for_settings,
    drag_selection_release,
    drive_hover_scheduler,
    duplicate_selected_zone,
    encode_context_capsule_envelope,
    encryption_mode_from_wire,
    encryption_mode_setting_command_for,
    ensure_suggestor_target_zone,
    export_recovery_diagnostics,
    finalize_item_drag_out,
    // #7 fix wave (2026-06-01) — W1/W3/P15 seams under test.
    focus_passphrase_field,
    focus_visible_zone,
    global_hotkey_command,
    global_hotkey_id,
    global_hotkey_modifiers,
    handle_bulk_manager_char,
    handle_bulk_manager_keydown,
    handle_bulk_manager_lbutton_up,
    handle_bulk_manager_text_edit_keydown,
    handle_icon_picker_keydown,
    handle_icon_picker_lbutton_up,
    handle_rules_wizard_char,
    handle_rules_wizard_keydown,
    handle_rules_wizard_lbutton_up,
    handle_settings_passphrase_char,
    handle_settings_text_char,
    handle_settings_text_keydown,
    handle_snapshot_picker_lbutton_up,
    handle_stack_bloom_lbutton_up,
    handle_stack_bloom_preview_lbutton_down,
    handle_stack_bloom_preview_lbutton_up,
    handle_stack_tray_lbutton_down,
    handle_stack_tray_lbutton_up,
    handle_suggestor_keydown,
    handle_suggestor_lbutton_up,
    handle_timeline_lbutton_up,
    handle_zone_editor_lbutton_up,
    hide_tooltip_payload,
    hides_when_workspace_aux_opens,
    highlight_overlay,
    hover_frame_pump_needed,
    hover_frame_timer_needed,
    icon_picker_slug_for_hit,
    import_theme_for_root,
    is_workspace_aux_surface,
    item_context_action_for_choice,
    item_context_dispatch_for_action,
    item_context_menu_rows,
    item_drag_target_zone_for_point,
    item_file_display_path,
    item_grid_position_for_drag_point,
    item_icon_startup_rehydrate_force,
    item_open_command_for_double_click,
    layout_new_auto_group_zones,
    list_context_capsules_for_path,
    list_pinned_minibar_labels,
    list_plugins_for_root,
    list_settings_backups_for_vault_path,
    load_available_theme_options,
    load_startup_zones_or_migrate_legacy,
    locale_setting_command_for,
    logical_viewport_from_device_size,
    match_context_window,
    minibar_command_for_pointer,
    move_zone_live,
    next_bulk_accent,
    next_bulk_alias,
    next_bulk_capsule_size,
    next_bulk_display_mode,
    next_icon_slug,
    next_palette_accent,
    next_stack_tray_member,
    next_update_frequency,
    normal_pointer_drag_active,
    normalize_icon_slug,
    normalized_rename_leaf,
    on_hover_target_changed,
    palette_picker,
    palette_picker_accent_for_hit,
    panel_header_button_hover_for_hit,
    parse_minibar_pin_ids,
    passphrase_button_command,
    persist_active_theme_to_vault,
    persist_keybinding_reset_to_vault,
    persist_passphrase_to_vault,
    persist_rule_run_stats,
    persist_setting_to_vault,
    persist_settings_accent_to_vault,
    persist_theme_base_accent_to_vault,
    persist_zone_display_mode_to_vault,
    pin_zone_minibar_state,
    poll_hover_scheduler,
    poll_stack_bloom_interaction,
    queue_add_items,
    queue_update_action,
    record_rule_execution_timeline_pair,
    recovery_vault_snapshot_from_vault,
    recycle_delete_flags,
    refresh_live_folder_zone,
    refresh_settings_plugins_for_root,
    rehydrate_live_folder_bindings_with,
    reset_pointer_drag_hover_channels,
    reset_settings_transient_state,
    resize_zone_live,
    restore_context_capsule_for_path,
    restore_latest_settings_backup_from_vault,
    restore_minibar_pins_from_wire_value,
    restore_recovery_bundle,
    restore_recovery_icon_backup_with,
    restore_recovery_vault_payload_to_vault,
    restore_settings_backup_by_id_from_vault,
    restore_timeline_checkpoint,
    reveal_stack_at_drop_pointer,
    rules_item_type_for_path,
    rules_preview_zones_from_app,
    rules_state_dir_for_zones_path,
    rules_zone_id_from_wire,
    run_interval_rule_for_scheduler_event_with_desktop,
    run_on_file_change_rules,
    sampled_zone_pill_morph,
    save_icon_picker,
    save_layout_snapshot,
    save_palette_picker,
    save_rule_for_state_dir,
    save_settings_general,
    save_timeline_checkpoint,
    search_icon_for_kind,
    seed_suggestor_from_files,
    settings_appearance_hover_for_hit,
    settings_aux_host_rect,
    settings_backup_file_name,
    settings_close_hover_for_hit,
    settings_encryption_mode_hover_for_hit,
    settings_wheel_scroll_delta_from_wparam,
    settle_inline_zone_search_animation,
    shell_file_list_from_path,
    should_start_background_update_check,
    should_start_item_drag_out,
    show_tooltip_payload,
    smart_group_zone_dimensions,
    snapshot_dir_for_zones_path,
    stack_aware_hover_zone_for_point,
    stack_bloom_cursor_watch_active,
    stack_bloom_hit_for_point,
    stack_bloom_hover_anchor_for_point,
    stack_bloom_hover_suppresses_main_tooltip,
    stack_bloom_preview_hit_for_point,
    stack_bloom_preview_item_hit_for_point,
    stack_bloom_reveal_progress_for_anchor,
    stamp_rule_id_if_empty,
    start_item_drag_out_with,
    startup_diag_skip_value,
    startup_heal_recovery_bundle,
    state_dir_for_root,
    theme_base_accent_from_wire,
    tick_pill_animator,
    tick_stack_bloom_animation,
    tick_zone_pill_animation,
    timeline_dir_for_zones_path,
    toggle_stack_bloom_from_capsule_click,
    tooltip_command_for_bulk_manager_hover,
    tooltip_command_for_capsule_picker_hover,
    tooltip_command_for_hover,
    tooltip_command_for_icon_picker_hover,
    tooltip_command_for_item_file_rename_hover,
    tooltip_command_for_main_hover,
    tooltip_command_for_minibar_hover,
    tooltip_command_for_palette_picker_hover,
    tooltip_command_for_rules_wizard_hover,
    tooltip_command_for_search_hover,
    tooltip_command_for_snapshot_picker_hover,
    tooltip_command_for_suggestor_hover,
    tooltip_command_for_timeline_hover,
    tooltip_command_for_zone_editor_hover,
    tooltip_uses_aux_surface,
    tray_command_for_callback,
    tray_menu_command_for_choice,
    tray_menu_command_for_item,
    ui,
    unlock_passphrase_vault,
    unpin_zone_minibar,
    update_check_interval,
    update_frequency_from_wire,
    update_frequency_setting_command_for,
    update_stack_bloom_hover,
    update_stack_bloom_petal_hover,
    update_zone_pill_hover,
    updater_event_should_auto_download,
    widen_static,
    window_kind_routes_settings_keydown,
    window_kind_routes_settings_pointer,
    with_app_viewport,
    write_minibar_pins_to_vault,
    zone_accepts_click_expand,
    zone_context_action_for_choice,
    zone_context_menu_rows,
    zone_display_mode_from_wire,
    zone_drag_pointer_offset,
    zone_item_max_scroll,
    zone_list_from_bento_zones,
    zone_pill_geometry,
    zone_scroll_target_for_point,
};
use bentodesk_app::business::bulk_manager_panel::{BulkTextEditField, SortKey};
use bentodesk_app::business::capsule_picker::{
    CapsuleEntry, capsule_picker_empty_rect, capsule_picker_error_rect, capsule_picker_hint_rect,
    capsule_picker_row_rect,
};
use bentodesk_app::business::rules_wizard;
use bentodesk_app::business::smart_group_suggestor;
use bentodesk_app::business::stack_tray;
use bentodesk_app::business::tray_menu::TrayMenuItem;
use bentodesk_app::business::{icons::IconKind, popover};
use bentodesk_app::dispatcher::PaletteTarget;
use bentodesk_app::item_file_rename_geometry::{
    item_file_rename_input_rect, item_file_rename_path_rect, item_file_rename_status_rect,
};
use bentodesk_app::picker_geometry::{
    IconPickerHit, PalettePickerHit, icon_picker_hit_test, icon_picker_slot_rect,
    palette_picker_clear_rect, palette_picker_hit_test, palette_picker_swatch_rect,
};
use bentodesk_app::state::{DEFAULT_COLLAPSE_DELAY_MS, DEFAULT_EXPAND_DELAY_MS, SettingsSnapshot};
// R14 supplement (2026-05-25) — `settings_update_auto_download_rect` and
// `settings_update_check_now_rect` removed from test-mod imports per
// bundle directive (clippy `unused_imports`). The fns live in
// `bentodesk_app::settings_panel` and remain accessible to production
// call sites; the test mod simply does not reference them.
use bentodesk_app::zone_editor_geometry::{
    ZoneEditorHit, zone_editor_accent_option_rect, zone_editor_cancel_rect, zone_editor_close_rect,
    zone_editor_grid_option_rect, zone_editor_grid_rect, zone_editor_hit_test,
    zone_editor_icon_rect, zone_editor_name_input_rect, zone_editor_save_rect,
};
use bentodesk_app::{
    AppState, BulkLayoutAlgorithm, IconPickerSession, ItemDragCandidate, ItemFileRenameSession,
    PalettePickerSession, PanelHeaderButtonHover, PanelHeaderButtonKind, SettingsBackupStatus,
    SettingsEncryptionMode, SettingsUpdaterStatus, ZoneDisplayMode, ZoneEditorSession,
};
use bentodesk_backend::config_vault::wire::ModeTag;
use bentodesk_backend::config_vault::{EncryptionMode as BackendEncryptionMode, Vault};
use bentodesk_backend::grouping::scanner::FileInfo;
use bentodesk_backend::rules::executor::{ActionEffect, ExecutionPlan};
use bentodesk_backend::rules::scheduler::SchedulerEvent;
use bentodesk_backend::rules::{Action, Condition, ConditionGroup, ConditionNode, RunMode};
use bentodesk_backend::search::SearchItemKind;
use bentodesk_backend::updater::{UpdateCheckFrequency, UpdateEvent, UpdateInfo, UpdateProgress};
use bentodesk_backend::watcher::FileChangedEvent;
use bentodesk_platform::{WindowKind, storage};
use bentodesk_style::Size;
use bentodesk_zone::{DEFAULT_ZONE_ICON, Zone, ZoneId, ZoneItem, ZoneItemId, ZoneList};
use smol_str::SmolStr;
use std::borrow::Cow;
use std::io::Write as _;
use windows_sys::Win32::UI::Shell::{
    FO_DELETE, FOF_ALLOWUNDO, FOF_WANTNUKEWARNING, NIF_GUID, NIF_ICON, NIF_MESSAGE, NIF_SHOWTIP,
    NIF_TIP, NIN_SELECT, NOTIFYICONDATAW,
};
use windows_sys::Win32::UI::WindowsAndMessaging::{WM_CONTEXTMENU, WM_LBUTTONUP, WM_RBUTTONUP};
use zip::write::FileOptions;

include!("tests/01_workspace_aux_surfaces_replace_superseded_tools_but_keep.rs");
include!("tests/02_tray_callback_maps_legacy_and_v4_events_to_commands.rs");
include!("tests/03_remove_item_restores_hidden_file_removes_item_and_persis.rs");
include!("tests/04_item_delete_recycle_success_removes_real_file_item_and_p.rs");
include!("tests/05_debug_overlay_toggle_command_flips_runtime_state.rs");
include!("tests/06_settings_restart_registration_is_bounded_and_resets_afte.rs");
include!("tests/07_tooltip_hover_timeline_row_text_tracks_cursor.rs");
include!("tests/08_tooltip_hover_item_file_rename_text_tracks_draft_status_.rs");
include!("tests/09_search_activation_for_action_queues_real_command.rs");
include!("tests/10_context_capsule_restore_uses_stable_id_not_raw_path.rs");
include!("tests/11_normalize_icon_slug_rejects_unknown_or_emoji_payloads.rs");
include!("tests/12_bulk_layout_algorithm_matches_tauri_row_column_shape.rs");
include!("tests/13_tauri_parity_duplicate_zone_hotkey_copies_visual_shell_o.rs");
include!("tests/14_startup_layout_prefers_non_empty_zones_bin_over_legacy_l.rs");
include!("tests/15_rules_wizard_pointer_close_button_clears_pending_action_.rs");
include!("tests/16_rule_execution_timeline_keeps_distinct_coalesce_keys.rs");
include!("tests/17_stack_bloom_hover_change_drives_time_based_reveal_progre.rs");
include!("tests/18_pill_hover_skips_stack_anchors.rs");
include!("tests/19_stack_tray_row_drag_dispatches_reorder_command.rs");
include!("tests/20_active_theme_applies_preextracted_plugin_provider_theme.rs");
include!("tests/21_settings_backup_list_and_restore_latest_round_trips_real.rs");
