use super::*;

impl Default for AppState {
    fn default() -> Self {
        Self::new()
    }
}

impl AppState {
    pub fn new() -> Self {
        Self {
            tree: Tree::with_capacity(64),
            viewport: Size::ZERO,
            zones: ZoneList::new(),
            next_zone_id: Cell::new(1),
            is_pinned: Cell::new(false),
            settings_open: Cell::new(false),
            settings_open_started_ms: Cell::new(0),
            settings_dirty: Cell::new(false),
            settings_save_error: RefCell::new(None),
            settings_draft_accent_color: RefCell::new(None),
            settings_accent_clear_requested: Cell::new(false),
            settings_snapshot: RefCell::new(None),
            scroll_offset_y: Cell::new(0.0),
            setting_desktop_embed: Cell::new(true),
            setting_autostart: Cell::new(false),
            setting_show_in_taskbar: Cell::new(false),
            setting_smart_layout: Cell::new(true),
            setting_portable_mode: Cell::new(false),
            desktop_sources: RefCell::new(Vec::new()),
            desktop_path_draft: RefCell::new(SmolStr::new_static("D:\\Desktop")),
            watch_paths_draft: RefCell::new(SmolStr::default()),
            settings_focused_field: Cell::new(SettingsTextField::None),
            expand_delay_ms: Cell::new(DEFAULT_EXPAND_DELAY_MS),
            collapse_delay_ms: Cell::new(DEFAULT_COLLAPSE_DELAY_MS),
            icon_cache_size: Cell::new(500),
            startup_high_priority: Cell::new(false),
            crash_restart_enabled: Cell::new(false),
            crash_max_retries: Cell::new(3),
            crash_window_secs: Cell::new(10),
            safe_start_after_hibernation: Cell::new(true),
            hibernate_resume_delay_ms: Cell::new(2000),
            update_check_frequency: Cell::new(UpdateCheckFrequency::Weekly),
            update_auto_download: Cell::new(true),
            settings_updater_status: RefCell::new(SettingsUpdaterStatus::Idle),
            stealth_enabled: Cell::new(true),
            stealth_status: RefCell::new(None),
            encryption_mode: Cell::new(SettingsEncryptionMode::None),
            passphrase_unlock_required: Cell::new(false),
            settings_encryption_status: RefCell::new(None),
            settings_encryption_mode_hover: Cell::new(None),
            settings_appearance_hover: Cell::new(None),
            settings_close_hover: Cell::new(false),
            passphrase_entry_active: Cell::new(false),
            passphrase_entry_purpose: Cell::new(PassphraseEntryPurpose::Set),
            passphrase_draft: RefCell::new(String::new()),
            theme_base_accent: RefCell::new(None),
            active_theme_id: RefCell::new(SmolStr::new_static("dark")),
            active_theme_name: RefCell::new(SmolStr::new_static("Dark")),
            active_theme_tokens: RefCell::new(DARK_DEFAULT.clone()),
            active_theme_tauri: RefCell::new(PALETTE_DARK),
            // M6b — default to the global dark/Rounded baseline; repopulated at
            // the `apply_active_theme` choke-point on boot-restore + live swap.
            active_theme_radius_tauri: RefCell::new(RADIUS),
            active_theme_shadow_tauri: RefCell::new(SHADOW),
            active_theme_typography_tauri: RefCell::new(TYPOGRAPHY),
            // M6c — dark default has no effect; repopulated at the choke-point.
            active_theme_effect_tauri: RefCell::new(EffectTauri::None),
            theme_transition_from_card: Cell::new(None),
            theme_transition_started_ms: Cell::new(0),
            theme_transition_active: Cell::new(false),
            available_themes: RefCell::new(Vec::new()),
            settings_theme_status: RefCell::new(None),
            zone_display_mode: Cell::new(ZoneDisplayMode::default()),
            hovered_zone: Cell::new(None),
            panel_header_button_hover: Cell::new(None),
            selected_zone: Cell::new(None),
            settings_backup_status: RefCell::new(None),
            settings_backup_entries: RefCell::new(Vec::new()),
            settings_plugin_entries: RefCell::new(Vec::new()),
            settings_plugin_status: RefCell::new(None),
            settings_plugin_uninstall_confirm: Cell::new(None),
            settings_owned_dialog_release_guard: Cell::new(false),
            settings_keybindings_open: Cell::new(false),
            settings_keybinding_recording: RefCell::new(None),
            settings_keybinding_feedback: RefCell::new(None),
            about_open: Cell::new(false),
            debug_overlay: RefCell::new(DebugOverlayState::default()),
            zones_path: PathBuf::new(),
            dirty: Cell::new(false),
            zone_drag: Cell::new(None),
            zone_drag_origin: Cell::new(None),
            zone_drag_body_visible_at_start: Cell::new(None),
            zone_drag_selected_before_start: Cell::new(None),
            zone_resize: Cell::new(None),
            item_drag: RefCell::new(None),
            stack_tray: RefCell::new(None),
            stack_tray_drag: Cell::new(None),
            stack_bloom_anchor: Cell::new(None),
            stack_bloom_leaving: Cell::new(false),
            stack_bloom_started_ms: Cell::new(0),
            stack_bloom_progress: Cell::new(1.0),
            stack_bloom_interaction: Cell::new(StackBloomInteractionState::default()),
            pill_animator: RefCell::new(Animator::new()),
            pill_pressed_zone: Cell::new(None),
            hover_scheduler: Cell::new(HoverScheduler::new()),
            item_hover: Cell::new(ItemHoverState::new()),
            zone_editor: RefCell::new(None),
            item_file_rename: RefCell::new(None),
            item_operation_status: RefCell::new(None),
            icon_picker: RefCell::new(None),
            palette_picker: RefCell::new(None),
            capsule_picker: RefCell::new(CapsulePickerState::new()),
            bulk_manager: RefCell::new(BulkManagerState::new()),
            bulk_manager_status: RefCell::new(None),
            rules_wizard: RefCell::new(RulesWizardState::new()),
            rules_wizard_rules: RefCell::new(Vec::new()),
            rules_wizard_rule_cursor: Cell::new(0),
            rules_wizard_delete_confirm: RefCell::new(None),
            rules_wizard_status: RefCell::new(None),
            timeline_panel: RefCell::new(TimelinePanelState::new()),
            snapshot_picker: RefCell::new(SnapshotPickerState::new()),
            search_bar: RefCell::new(SearchBarState::default()),
            zone_search_target: Cell::new(None),
            zone_search_closing: Cell::new(false),
            zone_search_last_interaction_ms: Cell::new(0),
            zone_content_scroll: Cell::new(None),
            zone_search_previous_foreground: Cell::new(0),
            search_status: RefCell::new(None),
            highlight_overlay: RefCell::new(HighlightOverlayState::new()),
            active_tooltip: RefCell::new(None),
            active_context_menu: RefCell::new(None),
            suggestor: RefCell::new(SuggestorState::new()),
            suggestor_status: RefCell::new(None),
            suggestor_dismissed: RefCell::new(HashSet::new()),
            minibars: RefCell::new(SmallVec::new()),
        }
    }
}
